
all: build 1 2 3 4 5 6 7

build:
	g++ -std=c++14 a.cpp

1:
	./a.out < 1.txt

2:
	./a.out < 2.txt

3:
	./a.out < 3.txt

4:
	./a.out < 4.txt

5:
	./a.out < 5.txt

6:
	./a.out < 6.txt

7:
	./a.out < 7.txt
