ec_2: ec
	./ec_ < ec_2.txt

ec_1: ec
	./ec_ < ec_1.txt

ec:
	g++ -std=c++11 -O2 -Wall -g ec.cpp -o ec_

ff1_1: ff1
	./ff1_ < ff1_1.txt

ff1:
	g++ -std=c++11 -O2 -Wall -g ff1.cpp -o ff1_

ff2_1: ff2
	./ff2_ < ff2_1.txt

ff2:
	g++ -std=c++11 -O2 -Wall -g ff2.cpp -o ff2_
